version: '3.1'
services:
  # The nginx Web Server
  web:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    ports:
      - ${DOCKER_WEB_PORT}:80
    volumes:
      - ./:/var/www:cached
      - ./docker/configs/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./docker/configs/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - "app"
      - "database"
    networks:
      - default_net
  # The PHP Application
  app:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    ports:
      - ${DOCKER_APP_PORT}:6001
    environment:
      # dev database
      DB_HOST: database
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./:/var/www:cached
      - ./docker/configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
    depends_on:
      - "database"
    networks:
      - default_net
  # The Database
  database:
    env_file:
      - .env
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_DATABASE}_root
    volumes:
        - ./docker/configs/mariadb/my.cnf:/etc/mysql/my.cnf
    ports:
      - ${DOCKER_DB_PORT}:3306
    networks:
      - default_net
  # Redis
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - default_net
networks:
  default_net:
    driver: bridge